spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 110MB
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.252:3306/ifiresens_v2?autoReconnect=true&useSSL=false
    username: ifire_usr
    password: ifU@S12!20
  sql:
    init:
      platform: mariadb
server:
  port: 8080
  servlet:
    session:
      timeout: 86400
mybatis:
  type-aliases-package: kr.fscom.firsens.sys.domain
  mapper-locations: classpath:mapper/**/*.xml
globals:
  naver:
    clientId: 'meqwtbwfkw'
custom:
  path:
    upload-images: 'D:/home/apps/img/imgstore/'
ifiresens:
  aeskey: QfTjWnZr4u7x!A%D*G-KaPdRgUkXp2s5

---
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 110MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.252:3306/ifiresens_v2?autoReconnect=true&useSSL=false
    username: ifire_usr
    password: ifU@S12!20
  sql:
    init:
      platform: mariadb
server:
  error:
    whitelabel:
      enabled: false
  port: 8443
  servlet:
    session:
      timeout: 86400
  ssl:
    enabled: true
    key-alias: securesign
    key-store-type: pkcs12
    key-store: /home/apps/ssl/fscom.kr.pkcs12
    key-store-password: dpvmdptm1!
    trust-store: /home/apps/ssl/fscom.kr.jks
    trust-store-password: dpvmdptm1!

logging:
  file:
    name: app
    path: ./logs/ss_firsens_mng/
mybatis:
  type-aliases-package: kr.fscom.firsens.sys.domain
  mapper-locations: classpath:mapper/**/*.xml
globals:
  naver:
    clientId: 'meqwtbwfkw'
custom:
  path:
    upload-images: '/home/apps/img/imgstore/'
ifiresens:
  aeskey: QfTjWnZr4u7x!A%D*G-KaPdRgUkXp2s5